import { ReactNode } from "react";
import { redirect } from "next/navigation";
import { supabaseServer } from "@/lib/supabaseServer";

const navItems = [
  { href: "/admin", label: "Overview" },
    { href: "/admin/users", label: "Usuarios" },
      { href: "/admin/products", label: "Productos" },
        { href: "/admin/orders", label: "Órdenes" },
          { href: "/admin/inventory", label: "Inventario" },
            { href: "/admin/invoices", label: "Facturas" },
              { href: "/admin/wallets", label: "Wallets" },
                { href: "/admin/fraud", label: "Fraude" },
                  { href: "/admin/support", label: "Soporte" },
                  ];

                  export default async function AdminLayout({
                    children,
                    }: {
                      children: ReactNode;
                      }) {
                        const supabase = await supabaseServer();

                          const {
                              data: { user },
                                } = await supabase.auth.getUser();

                                  if (!user?.email) {
                                      redirect("/login");
                                        }

                                          const { data: profile } = await supabase
                                              .from("profiles")
                                                  .select("role")
                                                      .eq("email", user.email)
                                                          .single();

                                                            if (!profile || !["admin", "super_admin"].includes(profile.role)) {
                                                                redirect("/dashboard");
                                                                  }

                                                                    return (
                                                                        <div className="min-h-screen bg-[#030b18] text-white">
                                                                              <div className="mx-auto max-w-7xl px-4 py-6 md:px-6 xl:px-8">
                                                                                      <header className="sticky top-0 z-30 rounded-[24px] border border-white/10 bg-[#081120]/85 px-4 py-4 backdrop-blur md:px-6">
                                                                                                <div className="flex flex-col gap-4">
                                                                                                            <div className="flex items-center justify-between gap-4">
                                                                                                                          <div className="flex min-w-0 items-center gap-3">
                                                                                                                                          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 font-bold text-white">
                                                                                                                                                            LS
                                                                                                                                                                            </div>

                                                                                                                                                                                            <div className="min-w-0">
                                                                                                                                                                                                              <p className="truncate text-base font-semibold">
                                                                                                                                                                                                                                  LinkStream Admin
                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                      <p className="truncate text-xs text-white/45">
                                                                                                                                                                                                                                                                                          Workspace premium · rol {profile.role}
                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                        href="/"
                                                                                                                                                                                                                                                                                                                                                                                        className="shrink-0 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/75 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                      Ver web
                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="/admin"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-xl border border-violet-400/20 bg-violet-500/10 px-4 py-2 text-sm text-violet-200"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        👑 Admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/seller"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/75 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🛍️ Vendedor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="/dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/75 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            👤 Comprador
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <nav className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {navItems.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={item.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href={item.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-white/70 transition hover:bg-white/[0.06] hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="pt-6">{children}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }