import { ReactNode } from "react";
import { redirect } from "next/navigation";
import { supabaseServer } from "@/lib/supabaseServer";

const navItems = [
  { href: "/admin", label: "Panel principal", icon: "🏠" },
    { href: "/admin/users", label: "Usuarios", icon: "👥" },
      { href: "/admin/products", label: "Productos", icon: "📦" },
        { href: "/admin/orders", label: "Órdenes", icon: "💳" },
          { href: "/admin/inventory", label: "Inventario", icon: "🗂️" },
            { href: "/admin/invoices", label: "Facturas", icon: "🧾" },
              { href: "/admin/wallets", label: "Wallets", icon: "💼" },
                { href: "/admin/fraud", label: "Fraude", icon: "⚠️" },
                  { href: "/admin/support", label: "Soporte", icon: "🎫" },
                  ];

                  export default async function AdminLayout({
                    children,
                    }: {
                      children: ReactNode;
                      }) {
                        const supabase = await supabaseServer();

                          const {
                              data: { user },
                                } = await supabase.auth.getUser();

                                  if (!user?.email) {
                                      redirect("/login");
                                        }

                                          const { data: profile } = await supabase
                                              .from("profiles")
                                                  .select("role")
                                                      .eq("email", user.email)
                                                          .single();

                                                            if (!profile || !["admin", "super_admin"].includes(profile.role)) {
                                                                redirect("/dashboard");
                                                                  }

                                                                    return (
                                                                        <div className="min-h-screen bg-[#030b18] text-white">
                                                                              <div className="mx-auto flex max-w-[1600px]">
                                                                                      <aside className="sticky top-0 hidden h-screen w-[280px] shrink-0 border-r border-white/10 bg-black/20 p-6 xl:block">
                                                                                                <div className="mb-8">
                                                                                                            <div className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 font-bold text-white">
                                                                                                                          LS
                                                                                                                                      </div>
                                                                                                                                                  <h2 className="mt-4 text-xl font-semibold">LinkStream Admin</h2>
                                                                                                                                                              <p className="mt-1 text-sm text-white/50">
                                                                                                                                                                            Control operativo y visión completa del negocio.
                                                                                                                                                                                        </p>
                                                                                                                                                                                                  </div>

                                                                                                                                                                                                            <nav className="space-y-2">
                                                                                                                                                                                                                        {navItems.map((item) => (
                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                      key={item.href}
                                                                                                                                                                                                                                                                      href={item.href}
                                                                                                                                                                                                                                                                                      className="flex items-center gap-3 rounded-2xl border border-transparent px-4 py-3 text-sm text-white/75 transition hover:border-white/10 hover:bg-white/[0.05] hover:text-white"
                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                    <span>{item.icon}</span>
                                                                                                                                                                                                                                                                                                                                    <span>{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                        </nav>

                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs uppercase tracking-[0.2em] text-white/40">
                                                                                                                                                                                                                                                                                                                                                                                                            Rol actual
                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-2 text-sm font-medium text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {profile.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 text-xs text-white/45">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Acceso propietario / desarrollador activo.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="min-w-0 flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <header className="sticky top-0 z-20 border-b border-white/10 bg-[#030b18]/85 backdrop-blur">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col gap-4 px-4 py-4 md:px-6 xl:px-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs uppercase tracking-[0.2em] text-white/40">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Admin workspace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="text-lg font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Vista de administración premium
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/70 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Ver web
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-wrap items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-sm text-white/55">Cambiar vista:</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/admin"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-xl border border-violet-400/20 bg-violet-500/10 px-4 py-2 text-sm text-violet-200"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      👑 Admin / Propietario
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/seller"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/75 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            🛍️ Vista vendedor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="/dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-sm text-white/75 hover:bg-white/[0.06]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🧑‍💻 Vista comprador
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="px-4 py-6 md:px-6 xl:px-8">{children}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }