import { supabaseServer } from "@/lib/supabaseServer";

function CardLink({
  href,
    title,
      description,
        emoji,
        }: {
          href: string;
            title: string;
              description: string;
                emoji: string;
                }) {
                  return (
                      <a
                            href={href}
                                  style={{
                                          display: "block",
                                                  padding: "20px",
                                                          borderRadius: "18px",
                                                                  textDecoration: "none",
                                                                          color: "white",
                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                          border: "1px solid rgba(255,255,255,0.08)",
                                                                                                }}
                                                                                                    >
                                                                                                          <div style={{ fontSize: "28px", marginBottom: "10px" }}>{emoji}</div>
                                                                                                                <div style={{ fontSize: "18px", fontWeight: 700 }}>{title}</div>
                                                                                                                      <div style={{ opacity: 0.7, marginTop: "8px", lineHeight: 1.5 }}>
                                                                                                                              {description}
                                                                                                                                    </div>
                                                                                                                                        </a>
                                                                                                                                          );
                                                                                                                                          }

                                                                                                                                          function Stat({
                                                                                                                                            title,
                                                                                                                                              value,
                                                                                                                                              }: {
                                                                                                                                                title: string;
                                                                                                                                                  value: number | string;
                                                                                                                                                  }) {
                                                                                                                                                    return (
                                                                                                                                                        <div
                                                                                                                                                              style={{
                                                                                                                                                                      padding: "18px",
                                                                                                                                                                              borderRadius: "16px",
                                                                                                                                                                                      background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                    }}
                                                                                                                                                                                                        >
                                                                                                                                                                                                              <div style={{ opacity: 0.7, fontSize: "14px" }}>{title}</div>
                                                                                                                                                                                                                    <div style={{ fontSize: "28px", fontWeight: 700, marginTop: "8px" }}>
                                                                                                                                                                                                                            {value}
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                        export default async function AdminPage() {
                                                                                                                                                                                                                                          const supabase = await supabaseServer();

                                                                                                                                                                                                                                            const { count: users } = await supabase
                                                                                                                                                                                                                                                .from("profiles")
                                                                                                                                                                                                                                                    .select("*", { count: "exact", head: true });

                                                                                                                                                                                                                                                      const { count: products } = await supabase
                                                                                                                                                                                                                                                          .from("products")
                                                                                                                                                                                                                                                              .select("*", { count: "exact", head: true });

                                                                                                                                                                                                                                                                const { count: orders } = await supabase
                                                                                                                                                                                                                                                                    .from("orders")
                                                                                                                                                                                                                                                                        .select("*", { count: "exact", head: true });

                                                                                                                                                                                                                                                                          const { count: tickets } = await supabase
                                                                                                                                                                                                                                                                              .from("support_tickets")
                                                                                                                                                                                                                                                                                  .select("*", { count: "exact", head: true });

                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                        <main
                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                      padding: "40px",
                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                      maxWidth: "1200px",
                                                                                                                                                                                                                                                                                                                              margin: "0 auto",
                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: "30px" }}>
                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                            display: "inline-block",
                                                                                                                                                                                                                                                                                                                                                                                        padding: "6px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "999px",
                                                                                                                                                                                                                                                                                                                                                                                                                background: "rgba(109,92,255,0.14)",
                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid rgba(109,92,255,0.25)",
                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#cfc7ff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Admin Center
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 style={{ fontSize: "36px", margin: 0 }}>Panel principal</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ opacity: 0.72, marginTop: "12px", lineHeight: 1.6 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Administra usuarios, productos, ventas, órdenes, fraude y soporte
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        desde un solo panel dentro de LinkStream.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gap: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "28px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Stat title="Usuarios" value={users ?? 0} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Stat title="Productos" value={products ?? 0} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Stat title="Órdenes" value={orders ?? 0} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Stat title="Tickets soporte" value={tickets ?? 0} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/users"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      emoji="👥"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title="Gestionar usuarios"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description="Cambiar roles, revisar cuentas, bloquear o moderar acceso."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/admin/products"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              emoji="🛒"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Productos marketplace"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description="Ver productos publicados, estado, precio y actividad del catálogo."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      emoji="💳"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title="Ventas y órdenes"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description="Revisar compras, pagos, estados de órdenes e ingresos."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/admin/fraud"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              emoji="⚠️"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Fraude"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description="Detectar actividad sospechosa, bloqueos y revisión manual."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/support"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      emoji="🎫"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title="Soporte"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description="Ver tickets, incidencias y reportes técnicos del sistema."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }