export default function AdminPage() {
          return (
              <main style={{ padding: "40px", color: "white" }}>
                    <h1 style={{ fontSize: "32px", marginBottom: "20px" }}>
                            Admin Center
                                  </h1>

                                        <div
                                                style={{
                                                          display: "grid",
                                                                    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
                                                                              gap: "20px",
                                                                                        marginTop: "30px",
                                                                                                }}
                                                                                                      >
                                                                                                              <a
                                                                                                                        href="/admin/users"
                                                                                                                                  style={{
                                                                                                                                              display: "block",
                                                                                                                                                          padding: "20px",
                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.1)",
                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                      textDecoration: "none",
                                                                                                                                                                                                                                  fontWeight: "600",
                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                              👥 Gestionar usuarios
                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                        href="/admin/products"
                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                              display: "block",
                                                                                                                                                                                                                                                                                                                          padding: "20px",
                                                                                                                                                                                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.1)",
                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                      textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "600",
                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                              🛒 Productos marketplace
                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/admin/orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "600",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              💳 Ventas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/admin/fraud"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "600",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ⚠️ Fraude
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/admin/support"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid rgba(255,255,255,0.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "600",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🎫 Soporte
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
}