import { supabaseServer } from "@/lib/supabaseServer";

export default async function AdminPage() {
  const supabase = await supabaseServer();

    const { data: users } = await supabase
        .from("profiles")
            .select("*")
                .order("created_at", { ascending: false });

                  const { data: products } = await supabase
                      .from("products")
                          .select("*");

                            const { data: orders } = await supabase
                                .from("orders")
                                    .select("*");

                                      const { data: tickets } = await supabase
                                          .from("support_tickets")
                                              .select("*")
                                                  .order("created_at", { ascending: false });

                                                    const safeUsers = users ?? [];
                                                      const safeProducts = products ?? [];
                                                        const safeOrders = orders ?? [];
                                                          const safeTickets = tickets ?? [];

                                                            return (
                                                                <main className="min-h-screen bg-[#030b18] px-4 py-8 text-white">
                                                                      <div className="mx-auto max-w-7xl space-y-6">
                                                                              <section className="rounded-3xl border border-white/10 bg-white/5 p-6 backdrop-blur">
                                                                                        <span className="inline-flex rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1 text-xs text-violet-200">
                                                                                                    Admin Center
                                                                                                              </span>

                                                                                                                        <h1 className="mt-4 text-4xl font-semibold">Panel de administración</h1>

                                                                                                                                  <p className="mt-3 max-w-2xl text-white/60">
                                                                                                                                              Control total de usuarios, productos, ventas, soporte y operación interna de LinkStream.
                                                                                                                                                        </p>
                                                                                                                                                                </section>

                                                                                                                                                                        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                                                                                                                                                                                  <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                              <p className="text-sm text-white/60">Usuarios</p>
                                                                                                                                                                                                          <h2 className="mt-2 text-3xl font-semibold">{safeUsers.length}</h2>
                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                              <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                          <p className="text-sm text-white/60">Productos</p>
                                                                                                                                                                                                                                                      <h2 className="mt-2 text-3xl font-semibold">{safeProducts.length}</h2>
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                          <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                                                                      <p className="text-sm text-white/60">Órdenes</p>
                                                                                                                                                                                                                                                                                                  <h2 className="mt-2 text-3xl font-semibold">{safeOrders.length}</h2>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                      <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-white/60">Tickets soporte</p>
                                                                                                                                                                                                                                                                                                                                              <h2 className="mt-2 text-3xl font-semibold">{safeTickets.length}</h2>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                        <section className="grid gap-6 xl:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-semibold">Usuarios recientes</h2>

                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-4 space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                        {safeUsers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-white/60">No hay usuarios todavía.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      safeUsers.slice(0, 8).map((user: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={user.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="rounded-2xl border border-white/10 bg-black/10 p-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="font-medium text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {user.email || "Sin email"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-1 text-sm text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Rol: {user.role || "user"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-1 text-sm text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Registro:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {user.created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? new Date(user.created_at).toLocaleString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "N/D"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-semibold">Tickets recientes</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-4 space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {safeTickets.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-white/60">No hay tickets todavía.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      safeTickets.slice(0, 8).map((ticket: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={ticket.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="rounded-2xl border border-white/10 bg-black/10 p-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="font-medium text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {ticket.subject || "Sin asunto"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-1 text-sm text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Estado: {ticket.status || "open"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-1 text-sm text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Tipo: {ticket.type || "general"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }