import { createClient } from "@supabase/supabase-js";
import Link from "next/link";

type InventoryRow = {
  id: string;
    account_email: string | null;
      delivery_reference: string | null;
        notes: string | null;
          status: string | null;
            products: any;
            };

            export default async function SellerInventoryPage() {

              const supabase = createClient(
                  process.env.NEXT_PUBLIC_SUPABASE_URL!,
                      process.env.SUPABASE_SERVICE_ROLE_KEY!
                        );

                          const { data: inventory, error } = await supabase
                              .from("inventory")
                                  .select(`
                                        id,
                                              account_email,
                                                    delivery_reference,
                                                          notes,
                                                                status,
                                                                      products (
                                                                              title
                                                                                    )
                                                                                        `)
                                                                                            .order("id", { ascending: false });

                                                                                              if (error) {
                                                                                                  throw new Error(`SELLER_INVENTORY_FETCH_ERROR: ${error.message}`);
                                                                                                    }

                                                                                                      const rows = (inventory as unknown as InventoryRow[]) || [];

                                                                                                        return (
                                                                                                            <main
                                                                                                                  style={{
                                                                                                                          padding: "40px",
                                                                                                                                  color: "white",
                                                                                                                                          maxWidth: "1100px",
                                                                                                                                                  margin: "0 auto",
                                                                                                                                                        }}
                                                                                                                                                            >
                                                                                                                                                                  <h1
                                                                                                                                                                          style={{
                                                                                                                                                                                    fontSize: "32px",
                                                                                                                                                                                              fontWeight: 700,
                                                                                                                                                                                                        margin: 0,
                                                                                                                                                                                                                }}
                                                                                                                                                                                                                      >
                                                                                                                                                                                                                              Inventario
                                                                                                                                                                                                                                    </h1>

                                                                                                                                                                                                                                          <p
                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                            marginTop: "8px",
                                                                                                                                                                                                                                                                      opacity: 0.6,
                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                            Cuentas disponibles para entregar.
                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: "18px" }}>
                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                          href="/seller"
                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                color: "rgba(255,255,255,0.7)",
                                                                                                                                                                                                                                                                                                                                                            textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                        fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                    ← Volver al panel seller
                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                          marginTop: "24px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overflow: "hidden",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gridTemplateColumns: "2fr 2fr 1fr",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gap: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderBottom: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Producto</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>Email</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>Status</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {rows.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            opacity: 0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              No hay inventario todavía.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rows.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gridTemplateColumns: "2fr 2fr 1fr",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gap: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderBottom: "1px solid rgba(255,255,255,0.06)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>{item.products?.title || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>{item.account_email || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>{item.status || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }