import { createClient } from "@supabase/supabase-js";
import { redirect } from "next/navigation";

type Product = {
  id: string;
    title: string;
      description: string | null;
        category: string | null;
          provider: string | null;
            plan_name: string | null;
              duration_days: number | null;
                price: number | null;
                  status: string | null;
                    created_at?: string | null;
                    };

                    function money(value: number | null | undefined) {
                      return new Intl.NumberFormat("es-MX", {
                          style: "currency",
                              currency: "USD",
                                  maximumFractionDigits: 2,
                                    }).format(value || 0);
                                    }

                                    function formatDate(value?: string | null) {
                                      if (!value) return "Sin fecha";
                                        try {
                                            return new Date(value).toLocaleString("es-MX");
                                              } catch {
                                                  return "Sin fecha";
                                                    }
                                                    }
                                                    async function setProductStatus(formData: FormData) {
                                                        "use server";

                                                          const productId = String(formData.get("product_id") || "");
                                                            const status = String(formData.get("status") || "");

                                                              if (!productId || !status) return;

                                                                const supabase = createClient(
                                                                    process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                        process.env.SUPABASE_SERVICE_ROLE_KEY!
                                                                          );

                                                                            const { error } = await supabase
                                                                                .from("products")
                                                                                    .update({ status })
                                                                                        .eq("id", productId);

                                                                                          if (error) {
                                                                                              throw new Error(`STATUS_UPDATE_ERROR: ${error.message}`);
                                                                                                }

                                                                                                  redirect("/admin/products");
                                                                                                  }

                                                                                                  async function deleteProduct(formData: FormData) {
                                                                                                    "use server";

                                                                                                      const productId = String(formData.get("product_id") || "");
                                                                                                        if (!productId) return;

                                                                                                          const supabase = createClient(
                                                                                                              process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                                                                  process.env.SUPABASE_SERVICE_ROLE_KEY!
                                                                                                                    );

                                                                                                                      const { error } = await supabase
                                                                                                                          .from("products")
                                                                                                                              .delete()
                                                                                                                                  .eq("id", productId);

                                                                                                                                    if (error) {
                                                                                                                                        throw new Error(`DELETE_PRODUCT_ERROR: ${error.message}`);
                                                                                                                                          }

                                                                                                                                            redirect("/admin/products");
                                                                                                                                            }
                                                                                                                                            export default async function AdminProductsPage() {
                                                                                                                                                const supabase = createClient(
                                                                                                                                                    process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                                                                                                        process.env.SUPABASE_SERVICE_ROLE_KEY!
                                                                                                                                                          );

                                                                                                                                                            const { data: products } = await supabase
                                                                                                                                                                .from("products")
                                                                                                                                                                    .select("*")
                                                                                                                                                                        .order("created_at", { ascending: false });

                                                                                                                                                                          const safeProducts: Product[] = products || [];

                                                                                                                                                                            return (
                                                                                                                                                                                <main style={{ padding: "32px", color: "white" }}>
                                                                                                                                                                                      <h1>Productos marketplace</h1>

                                                                                                                                                                                            <a
                                                                                                                                                                                                    href="/admin/products/new"
                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                      display: "inline-block",
                                                                                                                                                                                                                                marginTop: "10px",
                                                                                                                                                                                                                                          padding: "10px 16px",
                                                                                                                                                                                                                                                    borderRadius: "12px",
                                                                                                                                                                                                                                                              background: "linear-gradient(135deg,#7c3aed,#06b6d4)",
                                                                                                                                                                                                                                                                        color: "white",
                                                                                                                                                                                                                                                                                  textDecoration: "none",
                                                                                                                                                                                                                                                                                            fontWeight: 700,
                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                  + Crear producto
                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: "30px", display: "grid", gap: "16px" }}>
                                                                                                                                                                                                                                                                                                                                      {safeProducts.map((product) => (
                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                            key={product.id}
                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                    background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>{product.title}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ opacity: 0.7 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {product.description || "Sin descripción"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginTop: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Precio: {money(product.price)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginTop: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Estado: {product.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginTop: "16px", display: "flex", gap: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form action={setProductStatus}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="product_id" value={product.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name="status"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={product.status === "active" ? "inactive" : "active"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#334155",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.status === "active" ? "Pausar" : "Activar"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form action={setProductStatus}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="product_id" value={product.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="status" value="rejected" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "#f59e0b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Rechazar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form action={deleteProduct}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="hidden" name="product_id" value={product.id} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "#ef4444",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Eliminar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                            }