'use client'

import { useState } from 'react'

type Platform = {
  name: string
    logo: string
      domain: string
        plans: { name: string; price: number }[]
        }

        type Category = {
          title: string
            items: Platform[]
            }

            const categories: Category[] = [
              {
                  title: '🎬 Streaming',
                      items: [
                            { name: 'Netflix', logo: 'https://logo.clearbit.com/netflix.com', domain: 'netflix.com', plans: [{ name: 'Premium', price: 149 }] },
                                  { name: 'Disney+', logo: 'https://logo.clearbit.com/disneyplus.com', domain: 'disneyplus.com', plans: [{ name: 'Premium', price: 129 }] },
                                        { name: 'Prime Video', logo: 'https://logo.clearbit.com/primevideo.com', domain: 'primevideo.com', plans: [{ name: 'Mensual', price: 99 }] },
                                              { name: 'HBO Max', logo: 'https://logo.clearbit.com/hbomax.com', domain: 'hbomax.com', plans: [{ name: 'Estándar', price: 119 }] },
                                                    { name: 'Paramount+', logo: 'https://logo.clearbit.com/paramountplus.com', domain: 'paramountplus.com', plans: [{ name: 'Mensual', price: 79 }] },
                                                          { name: 'Crunchyroll', logo: 'https://logo.clearbit.com/crunchyroll.com', domain: 'crunchyroll.com', plans: [{ name: 'Premium', price: 79 }] },
                                                                { name: 'MUBI', logo: 'https://logo.clearbit.com/mubi.com', domain: 'mubi.com', plans: [{ name: 'Mensual', price: 89 }] },
                                                                      { name: 'Pluto TV', logo: 'https://logo.clearbit.com/pluto.tv', domain: 'pluto.tv', plans: [{ name: 'Gratis', price: 0 }] },
                                                                            { name: 'Tubi', logo: 'https://logo.clearbit.com/tubi.tv', domain: 'tubi.tv', plans: [{ name: 'Gratis', price: 0 }] },
                                                                                  { name: 'Plex', logo: 'https://logo.clearbit.com/plex.tv', domain: 'plex.tv', plans: [{ name: 'Gratis', price: 0 }] },
                                                                                      ],
                                                                                        },
                                                                                          {
                                                                                              title: '🎧 Música',
                                                                                                  items: [
                                                                                                        { name: 'Spotify', logo: 'https://logo.clearbit.com/spotify.com', domain: 'spotify.com', plans: [{ name: 'Premium', price: 59 }] },
                                                                                                              { name: 'Apple Music', logo: 'https://logo.clearbit.com/apple.com', domain: 'apple.com', plans: [{ name: 'Individual', price: 59 }] },
                                                                                                                    { name: 'Deezer', logo: 'https://logo.clearbit.com/deezer.com', domain: 'deezer.com', plans: [{ name: 'Premium', price: 49 }] },
                                                                                                                          { name: 'YouTube Music', logo: 'https://logo.clearbit.com/youtube.com', domain: 'youtube.com', plans: [{ name: 'Premium', price: 59 }] },
                                                                                                                                { name: 'Amazon Music', logo: 'https://logo.clearbit.com/music.amazon.com', domain: 'music.amazon.com', plans: [{ name: 'Mensual', price: 59 }] },
                                                                                                                                    ],
                                                                                                                                      },
                                                                                                                                      ]

                                                                                                                                      export default function Page() {
                                                                                                                                        const [selected, setSelected] = useState<Platform | null>(null)

                                                                                                                                          return (
                                                                                                                                              <main className="min-h-screen bg-[#05070d] text-white">

                                                                                                                                                    {/* NAVBAR */}
                                                                                                                                                          <header className="flex justify-between items-center px-8 py-5 border-b border-white/10 backdrop-blur bg-black/30 sticky top-0 z-50">
                                                                                                                                                                  <h1 className="font-semibold text-lg">LinkStream</h1>
                                                                                                                                                                          <div className="flex gap-6 text-sm text-white/60">
                                                                                                                                                                                    <span className="hover:text-white cursor-pointer">Marketplace</span>
                                                                                                                                                                                              <span className="hover:text-white cursor-pointer">Seller</span>
                                                                                                                                                                                                        <span className="hover:text-white cursor-pointer">Login</span>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                            {/* HERO */}
                                                                                                                                                                                                                                  <section className="relative py-24 px-6 text-center">
                                                                                                                                                                                                                                          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(120,119,255,0.25),transparent_70%)]" />
                                                                                                                                                                                                                                                  <div className="relative z-10">
                                                                                                                                                                                                                                                            <h1 className="text-5xl font-semibold mb-6">
                                                                                                                                                                                                                                                                        Bienvenido a LinkStream
                                                                                                                                                                                                                                                                                  </h1>
                                                                                                                                                                                                                                                                                            <p className="text-white/50 max-w-xl mx-auto">
                                                                                                                                                                                                                                                                                                        El paraíso del entretenimiento digital. Compra y vende cuentas premium en segundos.
                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                      {/* CATEGORÍAS */}
                                                                                                                                                                                                                                                                                                                                            {categories.map((cat) => (
                                                                                                                                                                                                                                                                                                                                                    <section key={cat.title} className="px-6 pb-12">

                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-white/60 mb-4">{cat.title}</h2>

                                                                                                                                                                                                                                                                                                                                                                        <div className="flex gap-5 overflow-x-auto">

                                                                                                                                                                                                                                                                                                                                                                                    {cat.items.map((p) => (
                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                  key={p.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setSelected(p)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="min-w-[200px] p-5 rounded-xl bg-white/5 border border-white/10 hover:scale-110 transition cursor-pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  src={p.logo}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alt={p.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="h-10 mb-4 object-contain"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onError={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.currentTarget.src = `https://logo.clearbit.com/${p.domain}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm">{p.name}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* MODAL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {selected && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="fixed inset-0 bg-black/70 flex items-center justify-center">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-[#0c0f1a] p-6 rounded-xl w-80 border border-white/10">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="mb-4">{selected.name}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {selected.plans.map((plan) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={plan.name} className="flex justify-between mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{plan.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>${plan.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="w-full mt-4 py-2 bg-purple-500 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Comprar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => setSelected(null)} className="mt-3 text-xs w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Cerrar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }