"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function BuyNowButton({
  productId,
    productTitle,
    }: {
      productId: string;
        productTitle: string;
        }) {
          const router = useRouter();
            const [buyerEmail, setBuyerEmail] = useState("");
              const [loading, setLoading] = useState(false);
                const [msg, setMsg] = useState<string | null>(null);

                  async function handleBuy() {
                      try {
                            setLoading(true);
                                  setMsg(null);

                                        const res = await fetch("/api/checkout", {
                                                method: "POST",
                                                        headers: {
                                                                  "Content-Type": "application/json",
                                                                          },
                                                                                  body: JSON.stringify({
                                                                                            productId,
                                                                                                      buyerEmail,
                                                                                                              }),
                                                                                                                    });

                                                                                                                          const data = await res.json();

                                                                                                                                if (!res.ok) {
                                                                                                                                        setMsg(data.error || "No se pudo completar la compra");
                                                                                                                                                setLoading(false);
                                                                                                                                                        return;
                                                                                                                                                              }

                                                                                                                                                                    const params = new URLSearchParams({
                                                                                                                                                                            orderId: data.orderId || "",
                                                                                                                                                                                    productTitle: data.delivery?.productTitle || productTitle || "",
                                                                                                                                                                                            accountEmail: data.delivery?.accountEmail || "",
                                                                                                                                                                                                    accountPassword: data.delivery?.accountPassword || "",
                                                                                                                                                                                                            deliveryReference: data.delivery?.deliveryReference || "",
                                                                                                                                                                                                                    notes: data.delivery?.notes || "",
                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                router.push(`/checkout/success?${params.toString()}`);
                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                          setMsg("Ocurrió un error inesperado");
                                                                                                                                                                                                                                                setLoading(false);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                          marginTop: "18px",
                                                                                                                                                                                                                                                                                  display: "grid",
                                                                                                                                                                                                                                                                                          gap: "12px",
                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                  type="email"
                                                                                                                                                                                                                                                                                                                          placeholder="Tu correo para recibir la compra"
                                                                                                                                                                                                                                                                                                                                  value={buyerEmail}
                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setBuyerEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                      minHeight: "48px",
                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                    background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleBuy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={loading || !buyerEmail}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: "50px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "linear-gradient(135deg,#7c3aed,#06b6d4)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          opacity: loading || !buyerEmail ? 0.7 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? "Procesando compra..." : "Comprar ahora"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {msg && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#fca5a5",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msg}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }