"use client";

import { useEffect, useState } from "react";

const platforms = [
  {
      name: "Netflix",
          logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
            },
              {
                  name: "Prime Video",
                      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Prime_Video.png",
                        },
                          {
                              name: "Disney+",
                                  logo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg",
                                    },
                                      {
                                          name: "HBO Max",
                                              logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/HBO_Max_Logo.svg",
                                                },
                                                  {
                                                      name: "Crunchyroll",
                                                          logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Crunchyroll_Logo.png",
                                                            },
                                                              {
                                                                  name: "Spotify",
                                                                      logo: "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg",
                                                                        },
                                                                        ];

                                                                        export default function Marketplace() {
                                                                          const [selected, setSelected] = useState<string | null>(null);
                                                                            const [listings, setListings] = useState<any[]>([]);

                                                                              useEffect(() => {
                                                                                  fetch("/api/listings")
                                                                                        .then((res) => res.json())
                                                                                              .then(setListings);
                                                                                                }, []);

                                                                                                  const filtered = listings.filter(
                                                                                                      (l) => l.platform === selected
                                                                                                        );

                                                                                                          return (
                                                                                                              <main className="min-h-screen bg-[#020617] text-white px-6 py-16">

                                                                                                                    {/* HEADER */}
                                                                                                                          <h1 className="text-4xl font-bold mb-10 tracking-tight">
                                                                                                                                  Marketplace
                                                                                                                                        </h1>

                                                                                                                                              {/* LOGOS GRID */}
                                                                                                                                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-16">

                                                                                                                                                            {platforms.map((p) => (
                                                                                                                                                                      <div
                                                                                                                                                                                  key={p.name}
                                                                                                                                                                                              onClick={() => setSelected(p.name)}
                                                                                                                                                                                                          className="group cursor-pointer p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur hover:scale-105 transition relative overflow-hidden"
                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                {/* glow */}
                                                                                                                                                                                                                                            <div className="absolute inset-0 bg-gradient-to-r from-purple-500/20 to-indigo-500/20 opacity-0 group-hover:opacity-100 blur-xl transition" />

                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                      src={p.logo}
                                                                                                                                                                                                                                                                                    alt={p.name}
                                                                                                                                                                                                                                                                                                  className="h-10 mx-auto object-contain relative z-10"
                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                ))}

                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                            {/* LISTINGS */}
                                                                                                                                                                                                                                                                                                                                                  {selected && (
                                                                                                                                                                                                                                                                                                                                                          <section className="animate-fadeIn">
                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-semibold mb-6">
                                                                                                                                                                                                                                                                                                                                                                                {selected}
                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                    {filtered.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-white/50">No hay productos aún</p>
                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid md:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {filtered.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="p-6 rounded-2xl bg-white/5 border border-white/10 hover:scale-105 transition backdrop-blur"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {item.plan_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ${(item.price_cents / 100).toFixed(0)} MXN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-white/40">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {item.capacity_total} cupos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="mt-4 w-full py-2 rounded-lg bg-gradient-to-r from-purple-500 to-indigo-500 hover:scale-105 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Comprar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }