import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
      const body = await req.json();

          const productId = String(body.productId || "").trim();
              const buyerEmail = String(body.buyerEmail || "").trim();

                  if (!productId || !buyerEmail) {
                        return NextResponse.json(
                                { error: "Faltan productId o buyerEmail" },
                                        { status: 400 }
                                              );
                                                  }

                                                      const supabase = createClient(
                                                            process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                  process.env.SUPABASE_SERVICE_ROLE_KEY!
                                                                      );

                                                                          const { data: product, error: productError } = await supabase
                                                                                .from("products")
                                                                                      .select("id,title,price,status")
                                                                                            .eq("id", productId)
                                                                                                  .single();

                                                                                                      if (productError || !product) {
                                                                                                            return NextResponse.json(
                                                                                                                    { error: "Producto no encontrado" },
                                                                                                                            { status: 404 }
                                                                                                                                  );
                                                                                                                                      }

                                                                                                                                          if (product.status !== "active") {
                                                                                                                                                return NextResponse.json(
                                                                                                                                                        { error: "Producto no disponible" },
                                                                                                                                                                { status: 400 }
                                                                                                                                                                      );
                                                                                                                                                                          }

                                                                                                                                                                              const { data: inventoryItem, error: inventoryFetchError } = await supabase
                                                                                                                                                                                    .from("inventory")
                                                                                                                                                                                          .select("id,account_email,account_password,delivery_reference,notes,status")
                                                                                                                                                                                                .eq("product_id", productId)
                                                                                                                                                                                                      .eq("status", "available")
                                                                                                                                                                                                            .order("id", { ascending: true })
                                                                                                                                                                                                                  .limit(1)
                                                                                                                                                                                                                        .single();

                                                                                                                                                                                                                            if (inventoryFetchError || !inventoryItem) {
                                                                                                                                                                                                                                  return NextResponse.json(
                                                                                                                                                                                                                                          { error: "No hay inventario disponible para este producto" },
                                                                                                                                                                                                                                                  { status: 400 }
                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                const { data: order, error: orderError } = await supabase
                                                                                                                                                                                                                                                                      .from("orders")
                                                                                                                                                                                                                                                                            .insert({
                                                                                                                                                                                                                                                                                    product_id: product.id,
                                                                                                                                                                                                                                                                                            buyer_email: buyerEmail,
                                                                                                                                                                                                                                                                                                    amount: product.price,
                                                                                                                                                                                                                                                                                                            status: "paid",
                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                        .select("id")
                                                                                                                                                                                                                                                                                                                              .single();

                                                                                                                                                                                                                                                                                                                                  if (orderError || !order) {
                                                                                                                                                                                                                                                                                                                                        return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                { error: "No se pudo crear la orden" },
                                                                                                                                                                                                                                                                                                                                                        { status: 500 }
                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                      const { error: inventoryUpdateError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                            .from("inventory")
                                                                                                                                                                                                                                                                                                                                                                                  .update({
                                                                                                                                                                                                                                                                                                                                                                                          status: "sold",
                                                                                                                                                                                                                                                                                                                                                                                                  sold_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                          order_id: order.id,
                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                      .eq("id", inventoryItem.id);

                                                                                                                                                                                                                                                                                                                                                                                                                          if (inventoryUpdateError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                        { error: "La orden se creó pero no se pudo actualizar inventario" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          orderId: order.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                delivery: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        productTitle: product.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                accountEmail: inventoryItem.account_email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accountPassword: inventoryItem.account_password,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                deliveryReference: inventoryItem.delivery_reference,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        notes: inventoryItem.notes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { error: error?.message || "Error interno del servidor" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }