"use client";

import { useState } from "react";

export default function Checkout() {
  const [loading, setLoading] = useState(false);

    const handlePay = () => {
        setLoading(true);

            setTimeout(() => {
                  window.location.href = "/checkout/success";
                      }, 2000);
                        };

                          return (
                              <main className="min-h-screen bg-black text-white flex items-center justify-center px-4">

                                    <div className="w-full max-w-md bg-white/5 border border-white/10 backdrop-blur-xl rounded-2xl p-6 shadow-xl">

                                            {/* HEADER */}
                                                    <h1 className="text-2xl font-bold mb-2 text-center">
                                                              Checkout
                                                                      </h1>

                                                                              <p className="text-center text-white/60 mb-6 text-sm">
                                                                                        Finaliza tu compra de forma segura
                                                                                                </p>

                                                                                                        {/* PRODUCTO */}
                                                                                                                <div className="bg-white/5 border border-white/10 rounded-xl p-4 mb-6">
                                                                                                                          <h2 className="font-semibold mb-1">Cuenta Premium</h2>
                                                                                                                                    <p className="text-white/60 text-sm mb-2">Servicio digital</p>

                                                                                                                                              <div className="flex justify-between items-center">
                                                                                                                                                          <span className="text-green-400 text-lg font-bold">
                                                                                                                                                                        $65 MXN
                                                                                                                                                                                    </span>
                                                                                                                                                                                                <span className="line-through text-white/40 text-sm">
                                                                                                                                                                                                              $120 MXN
                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                    {/* INPUTS */}
                                                                                                                                                                                                                                                            <div className="space-y-3 mb-6">
                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                              placeholder="Nombre en la tarjeta"
                                                                                                                                                                                                                                                                                                          className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm outline-none"
                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                                                      placeholder="Número de tarjeta"
                                                                                                                                                                                                                                                                                                                                                                  className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm outline-none"
                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="MM/AA"
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-1/2 bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="CVV"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-1/2 bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* BOTÓN */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handlePay}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full bg-gradient-to-r from-green-400 to-emerald-500 py-2 rounded-lg font-semibold hover:scale-105 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Procesando..." : "Pagar ahora"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* FOOTER */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-center text-xs text-white/40 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🔒 Pago seguro encriptado
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }