"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabase";

export default function SignUp() {
  const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
      const [loading, setLoading] = useState(false);
        const [msg, setMsg] = useState("");
          const [errorMsg, setErrorMsg] = useState("");

            const handleSignUp = async () => {
                setLoading(true);
                    setErrorMsg("");
                        setMsg("");

                            if (!email || !password) {
                                  setErrorMsg("Completa todos los campos");
                                        setLoading(false);
                                              return;
                                                  }

                                                      if (password.length < 6) {
                                                            setErrorMsg("La contraseña debe tener al menos 6 caracteres");
                                                                  setLoading(false);
                                                                        return;
                                                                            }

                                                                                const { error } = await supabase.auth.signUp({
                                                                                      email,
                                                                                            password,
                                                                                                });

                                                                                                    if (error) {
                                                                                                          setErrorMsg(error.message);
                                                                                                                setLoading(false);
                                                                                                                    } else {
                                                                                                                          setMsg("Revisa tu correo para confirmar tu cuenta 📩");
                                                                                                                                setLoading(false);
                                                                                                                                    }
                                                                                                                                      };

                                                                                                                                        return (
                                                                                                                                            <main className="min-h-screen bg-black text-white flex items-center justify-center px-4">

                                                                                                                                                  <div className="w-full max-w-md bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-xl">

                                                                                                                                                          {/* HEADER */}
                                                                                                                                                                  <h1 className="text-2xl font-bold text-center mb-2">
                                                                                                                                                                            Crear cuenta 🚀
                                                                                                                                                                                    </h1>

                                                                                                                                                                                            <p className="text-center text-white/60 mb-6 text-sm">
                                                                                                                                                                                                      Empieza en LinkStream en segundos
                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                      {/* MENSAJE OK */}
                                                                                                                                                                                                                              {msg && (
                                                                                                                                                                                                                                        <div className="bg-green-500/10 border border-green-500/20 text-green-400 text-sm p-2 rounded mb-4 text-center">
                                                                                                                                                                                                                                                    {msg}
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                              {/* ERROR */}
                                                                                                                                                                                                                                                                                      {errorMsg && (
                                                                                                                                                                                                                                                                                                <div className="bg-red-500/10 border border-red-500/20 text-red-400 text-sm p-2 rounded mb-4 text-center">
                                                                                                                                                                                                                                                                                                            {errorMsg}
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                      {/* EMAIL */}
                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                                                                                                                  placeholder="Correo electrónico"
                                                                                                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                className="w-full mb-3 p-3 bg-black/40 border border-white/10 rounded-lg outline-none focus:border-green-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                {/* PASSWORD */}
                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Contraseña"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full mb-4 p-3 bg-black/40 border border-white/10 rounded-lg outline-none focus:border-green-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* BOTÓN */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={handleSignUp}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full bg-gradient-to-r from-green-400 to-emerald-500 py-3 rounded-lg font-semibold hover:scale-105 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Creando cuenta..." : "Registrarse"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* LINK LOGIN */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-center text-white/50 text-sm mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ¿Ya tienes cuenta?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="/login" className="text-green-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Iniciar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }