import { createClient } from "@supabase/supabase-js";
import Link from "next/link";

type Product = {
  id: string;
    title: string;
      description: string | null;
        category: string | null;
          provider: string | null;
            plan_name: string | null;
              duration_days: number | null;
                price: number | null;
                  status: string | null;
                    created_by_role: string | null;
                    };

                    function money(value: number | null | undefined) {
                      return new Intl.NumberFormat("es-MX", {
                          style: "currency",
                              currency: "USD",
                                }).format(value || 0);
                                }

                                export default async function SellerProductsPage() {
                                  const supabase = createClient(
                                      process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                          process.env.SUPABASE_SERVICE_ROLE_KEY!
                                            );

                                              const { data: products } = await supabase
                                                  .from("products")
                                                      .select("*")
                                                          .eq("created_by_role", "seller")
                                                              .order("id", { ascending: false });

                                                                const safeProducts: Product[] = products || [];

                                                                  return (
                                                                      <main
                                                                            style={{
                                                                                    padding: "40px",
                                                                                            color: "white",
                                                                                                    maxWidth: "1100px",
                                                                                                            margin: "0 auto",
                                                                                                                  }}
                                                                                                                      >
                                                                                                                            <div style={{ display: "flex", justifyContent: "space-between", gap: "16px", flexWrap: "wrap" }}>
                                                                                                                                    <div>
                                                                                                                                              <h1 style={{ fontSize: "32px", fontWeight: 700, margin: 0 }}>
                                                                                                                                                          Mis productos
                                                                                                                                                                    </h1>
                                                                                                                                                                              <p style={{ marginTop: "8px", opacity: 0.6 }}>
                                                                                                                                                                                          Productos enviados por vendedores.
                                                                                                                                                                                                    </p>
                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                              href="/seller/products/new"
                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                    display: "inline-flex",
                                                                                                                                                                                                                                                                alignItems: "center",
                                                                                                                                                                                                                                                                            padding: "12px 16px",
                                                                                                                                                                                                                                                                                        borderRadius: "14px",
                                                                                                                                                                                                                                                                                                    background: "linear-gradient(135deg,#7c3aed,#06b6d4)",
                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                            textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                        fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                    height: "fit-content",
                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                + Crear producto
                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginTop: "18px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                      href="/seller"
                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ color: "rgba(255,255,255,0.7)", textDecoration: "none", fontSize: "14px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ← Volver al panel seller
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "24px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {safeProducts.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  No hay productos de seller todavía.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              safeProducts.map((product) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key={product.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 style={{ fontSize: "20px", fontWeight: 700, margin: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {product.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ opacity: 0.7, marginTop: "8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {product.description || "Sin descripción"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: "12px", display: "grid", gap: "6px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Categoría: {product.category || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Proveedor: {product.provider || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Plan: {product.plan_name || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Duración: {product.duration_days || "-"} días</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontWeight: 700 }}>Precio: {money(product.price)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>Estado: {product.status || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }