import { createClient } from "@supabase/supabase-js";
import { redirect } from "next/navigation";

async function createSellerProduct(formData: FormData) {
  "use server";

    const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
            process.env.SUPABASE_SERVICE_ROLE_KEY!
              );

                const title = String(formData.get("title") || "").trim();
                  const description = String(formData.get("description") || "").trim();
                    const category = String(formData.get("category") || "").trim();
                      const provider = String(formData.get("provider") || "").trim();
                        const planName = String(formData.get("plan_name") || "").trim();
                          const durationDays = Number(formData.get("duration_days") || 30);
                            const price = Number(formData.get("price") || 0);

                              if (!title || !category || !price) {
                                  throw new Error("Faltan title, category o price");
                                    }

                                      const { error } = await supabase.from("products").insert({
                                          title,
                                              description,
                                                  category,
                                                      provider,
                                                          plan_name: planName,
                                                              duration_days: durationDays,
                                                                  price,
                                                                      status: "pending_review",
                                                                          created_by_role: "seller",
                                                                            });

                                                                              if (error) {
                                                                                  throw new Error(`SELLER_PRODUCT_INSERT_ERROR: ${error.message}`);
                                                                                    }

                                                                                      redirect("/seller");
                                                                                      }

                                                                                      export default function SellerNewProductPage() {
                                                                                        return (
                                                                                            <main style={{ maxWidth: 900, margin: "40px auto", color: "white", padding: 32 }}>
                                                                                                  <a
                                                                                                          href="/seller"
                                                                                                                  style={{ color: "rgba(255,255,255,0.7)", textDecoration: "none", fontSize: 14 }}
                                                                                                                        >
                                                                                                                                ← Volver a seller
                                                                                                                                      </a>

                                                                                                                                            <div
                                                                                                                                                    style={{
                                                                                                                                                              marginTop: 20,
                                                                                                                                                                        border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                  background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                            borderRadius: 24,
                                                                                                                                                                                                      padding: 24,
                                                                                                                                                                                                              }}
                                                                                                                                                                                                                    >
                                                                                                                                                                                                                            <h1 style={{ fontSize: 32, fontWeight: 700, margin: 0 }}>
                                                                                                                                                                                                                                      Crear producto vendedor
                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                      <p style={{ marginTop: 10, color: "rgba(255,255,255,0.6)", fontSize: 14 }}>
                                                                                                                                                                                                                                                                Este producto quedará pendiente de aprobación.
                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                <form action={createSellerProduct} style={{ display: "grid", gap: 16, marginTop: 24 }}>
                                                                                                                                                                                                                                                                                          <input name="title" placeholder="Título del producto" required style={inputStyle} />
                                                                                                                                                                                                                                                                                                    <textarea name="description" placeholder="Descripción" rows={4} style={textareaStyle} />
                                                                                                                                                                                                                                                                                                              <input name="category" placeholder="Categoría" required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                        <input name="provider" placeholder="Proveedor" style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                  <input name="plan_name" placeholder="Plan" style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                        name="duration_days"
                                                                                                                                                                                                                                                                                                                                                                    type="number"
                                                                                                                                                                                                                                                                                                                                                                                placeholder="Duración en días"
                                                                                                                                                                                                                                                                                                                                                                                            defaultValue={30}
                                                                                                                                                                                                                                                                                                                                                                                                        style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                        name="price"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                step="0.01"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Precio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "linear-gradient(135deg,#7c3aed,#06b6d4)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Enviar a revisión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const inputStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    minHeight: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const textareaStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resize: "vertical",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };