import Link from "next/link";

function Card({
  href,
    title,
      subtitle,
      }: {
        href: string;
          title: string;
            subtitle: string;
            }) {
              return (
                  <Link
                        href={href}
                              style={{
                                      display: "flex",
                                              flexDirection: "column",
                                                      justifyContent: "center",
                                                              padding: "22px",
                                                                      borderRadius: "16px",
                                                                              background: "rgba(255,255,255,0.05)",
                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                              color: "white",
                                                                                                      textDecoration: "none",
                                                                                                              fontWeight: 700,
                                                                                                                      minHeight: "110px",
                                                                                                                            }}
                                                                                                                                >
                                                                                                                                      <span style={{ fontSize: "18px" }}>{title}</span>
                                                                                                                                            <span
                                                                                                                                                    style={{
                                                                                                                                                              fontSize: "13px",
                                                                                                                                                                        marginTop: "8px",
                                                                                                                                                                                  opacity: 0.7,
                                                                                                                                                                                            fontWeight: 400,
                                                                                                                                                                                                    }}
                                                                                                                                                                                                          >
                                                                                                                                                                                                                  {subtitle}
                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                              );
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              export default function SellerDashboard() {
                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                    <main
                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                  padding: "40px",
                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                  maxWidth: "1100px",
                                                                                                                                                                                                                                                                          margin: "0 auto",
                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                          <h1
                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                            fontSize: "34px",
                                                                                                                                                                                                                                                                                                                      fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                margin: 0,
                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                      Panel de vendedor
                                                                                                                                                                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "10px",
                                                                                                                                                                                                                                                                                                                                                                                              color: "rgba(255,255,255,0.6)",
                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                    Administra tus productos, inventario, ventas y ganancias.
                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gap: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/seller/products/new"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "linear-gradient(135deg,#7c3aed,#06b6d4)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  minHeight: "110px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: "18px" }}>Crear producto</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "13px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              opacity: 0.9,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Enviar producto a revisión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/seller/products"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title="Mis productos"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      subtitle="Ver productos creados y su estado"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/seller/inventory"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title="Inventario"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitle="Gestionar cuentas disponibles"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="/seller/orders"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Ventas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  subtitle="Ver órdenes y entregas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/seller/wallet"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title="Wallet"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitle="Ver ganancias y balances"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }