import { createClient } from "@supabase/supabase-js";
import Link from "next/link";

type Order = {
  id: string;
    amount: number | null;
      status: string | null;
        created_at: string | null;
        };

        function money(value: number | null | undefined) {
          return new Intl.NumberFormat("es-MX", {
              style: "currency",
                  currency: "USD",
                    }).format(value || 0);
                    }

                    function formatDate(value?: string | null) {
                      if (!value) return "Sin fecha";
                        try {
                            return new Date(value).toLocaleString("es-MX");
                              } catch {
                                  return "Sin fecha";
                                    }
                                    }

                                    export default async function SellerOrdersPage() {
                                      const supabase = createClient(
                                          process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                              process.env.SUPABASE_SERVICE_ROLE_KEY!
                                                );

                                                  const { data: orders } = await supabase
                                                      .from("orders")
                                                          .select("*")
                                                              .order("created_at", { ascending: false });

                                                                const safeOrders: Order[] = orders || [];

                                                                  return (
                                                                      <main
                                                                            style={{
                                                                                    padding: "40px",
                                                                                            color: "white",
                                                                                                    maxWidth: "1100px",
                                                                                                            margin: "0 auto",
                                                                                                                  }}
                                                                                                                      >
                                                                                                                            <h1 style={{ fontSize: "32px", fontWeight: 700, margin: 0 }}>
                                                                                                                                    Ventas seller
                                                                                                                                          </h1>

                                                                                                                                                <p style={{ marginTop: "8px", opacity: 0.6 }}>
                                                                                                                                                        Órdenes registradas y pagos.
                                                                                                                                                              </p>

                                                                                                                                                                    <div style={{ marginTop: "18px" }}>
                                                                                                                                                                            <Link
                                                                                                                                                                                      href="/seller"
                                                                                                                                                                                                style={{ color: "rgba(255,255,255,0.7)", textDecoration: "none", fontSize: "14px" }}
                                                                                                                                                                                                        >
                                                                                                                                                                                                                  ← Volver al panel seller
                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                        marginTop: "24px",
                                                                                                                                                                                                                                                                  display: "grid",
                                                                                                                                                                                                                                                                            gap: "16px",
                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                  {safeOrders.length === 0 ? (
                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                    background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                  No hay órdenes todavía.
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                              safeOrders.map((order) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key={order.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "rgba(255,255,255,0.04)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>Orden: {order.id}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: "6px" }}>Estado: {order.status || "-"}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginTop: "6px", fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Monto: {money(order.amount)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: "6px", opacity: 0.7 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Fecha: {formatDate(order.created_at)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }