import { supabaseServer } from "@/lib/supabaseServer";

function formatDate(value?: string | null) {
  if (!value) return "N/D";
    try {
        return new Date(value).toLocaleString();
          } catch {
              return "N/D";
                }
                }

                export default async function AdminInvoicesPage() {
                  const supabase = await supabaseServer();

                    const { data: invoices } = await supabase
                        .from("invoices")
                            .select("*")
                                .order("issued_at", { ascending: false });

                                  const safeInvoices = invoices ?? [];

                                    return (
                                        <main className="min-h-screen bg-[#030b18] p-8 text-white">
                                              <h1 className="mb-6 text-3xl font-semibold">Facturas</h1>

                                                    <div className="space-y-4">
                                                            {safeInvoices.length === 0 ? (
                                                                      <p>No hay facturas todavía.</p>
                                                                              ) : (
                                                                                        safeInvoices.map((invoice: any) => (
                                                                                                    <div
                                                                                                                  key={invoice.id}
                                                                                                                                className="rounded-xl border border-white/10 bg-white/5 p-4"
                                                                                                                                            >
                                                                                                                                                          <p className="font-semibold">
                                                                                                                                                                          {invoice.product_title}
                                                                                                                                                                                        </p>
                                                                                                                                                                                                      <p className="text-sm text-white/60">
                                                                                                                                                                                                                      Cliente: {invoice.buyer_email}
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                  <p className="text-sm text-white/60">
                                                                                                                                                                                                                                                                  Plan: {invoice.plan_name || "N/D"}
                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                              <p className="text-sm text-white/60">
                                                                                                                                                                                                                                                                                                              Duración: {invoice.duration_days} días
                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-white/60">
                                                                                                                                                                                                                                                                                                                                                          Total: {invoice.total_amount} {invoice.currency}
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                      Referencia: {invoice.payment_reference || "N/D"}
                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Fecha: {formatDate(invoice.issued_at)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }